/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author pc
 */
import civitas.Diario;
public class DiarioDialog extends javax.swing.JDialog {
    private Diario diario =  Diario.getInstance();
    /**
     * Creates new form DiarioDialog
     * @param parent
     */
    public DiarioDialog(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
        setLocationRelativeTo(null);
        mostrarEventos();
    }
    void mostrarEventos()
    {
        if(Diario.getInstance().eventosPendientes())
        {
            String txt="";
            while(Diario.getInstance().eventosPendientes())
            {
                txt += Diario.getInstance().leerEvento() +"\n";
            }
            txt_eventos.setText(txt);
        }
        this.setVisible(true);
        repaint();
        revalidate();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_eventos = new javax.swing.JLabel();
        boton_ok = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_eventos = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lb_eventos.setFont(new java.awt.Font("Waree", 0, 15)); // NOI18N
        lb_eventos.setText("Eventos del Diario: ");
        lb_eventos.setEnabled(false);

        boton_ok.setFont(new java.awt.Font("Waree", 1, 15)); // NOI18N
        boton_ok.setText("OK");
        boton_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_okActionPerformed(evt);
            }
        });

        txt_eventos.setColumns(20);
        txt_eventos.setFont(new java.awt.Font("Waree", 0, 15)); // NOI18N
        txt_eventos.setRows(5);
        txt_eventos.setDisabledTextColor(java.awt.Color.black);
        txt_eventos.setEnabled(false);
        jScrollPane1.setViewportView(txt_eventos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_eventos)
                    .addComponent(boton_ok, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lb_eventos)
                        .addGap(168, 168, 168)
                        .addComponent(boton_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_okActionPerformed
        this.dispose();
    }//GEN-LAST:event_boton_okActionPerformed
    /*
    
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DiarioDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DiarioDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DiarioDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DiarioDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                DiarioDialog dialog = new DiarioDialog(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }
//    */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_ok;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_eventos;
    private javax.swing.JTextArea txt_eventos;
    // End of variables declaration//GEN-END:variables
}
