/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import civitas.Jugador;
import civitas.TituloPropiedad;
import java.util.ArrayList;
/**
 *
 * @author pc
 */
public class JugadorPanel extends javax.swing.JPanel {
    Jugador jugador;
    
    /**
     * Creates new form JugadorPanel
     */
    public JugadorPanel() {
        initComponents();
    }
    public void setJugador(Jugador player)
    {
        jugador=player;
        txt_nombre.setText(jugador.getNombre());
        txt_saldo.setText(Float.toString(jugador.getSaldo()));
        txt_encarcelado.setText(Boolean.toString(jugador.isEncarcelado()));
        txt_especulador.setText(Boolean.toString(jugador.getEspeculador()));
        
        rellenaPropiedades(jugador.getPropiedades());
        
        repaint();
        
    }
    private void rellenaPropiedades(ArrayList<TituloPropiedad> lista){
        // Se elimina la información antigua
        panel_propiedades.removeAll();
        // Se recorre la lista de propiedades para ir creando sus vistas individuales y
        //añadirlas al panel
        for (TituloPropiedad t : lista) {
            PropiedadPanel vistaPropiedad = new PropiedadPanel();
            vistaPropiedad.setPropiedad(t);
            panel_propiedades.add(vistaPropiedad);
            vistaPropiedad.setVisible(true);
     }
     // Se fuerza la actualización visual del panel propiedades y del panel del jugador
     repaint();
     revalidate();

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jg_nom = new javax.swing.JLabel();
        jg_saldo = new javax.swing.JLabel();
        jg_encarcelado = new javax.swing.JLabel();
        jg_especulador = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        txt_saldo = new javax.swing.JTextField();
        txt_encarcelado = new javax.swing.JTextField();
        txt_especulador = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        panel_propiedades = new javax.swing.JPanel();

        jg_nom.setBackground(java.awt.Color.black);
        jg_nom.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jg_nom.setForeground(java.awt.Color.black);
        jg_nom.setText("Nombre: ");
        jg_nom.setEnabled(false);

        jg_saldo.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jg_saldo.setText("Saldo: ");
        jg_saldo.setEnabled(false);

        jg_encarcelado.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jg_encarcelado.setText("Encarcelado: ");
        jg_encarcelado.setEnabled(false);

        jg_especulador.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jg_especulador.setText("Especulador: ");
        jg_especulador.setEnabled(false);

        txt_nombre.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        txt_nombre.setEnabled(false);

        txt_saldo.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        txt_saldo.setEnabled(false);

        txt_encarcelado.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        txt_encarcelado.setEnabled(false);
        txt_encarcelado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_encarceladoActionPerformed(evt);
            }
        });

        txt_especulador.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        txt_especulador.setEnabled(false);
        txt_especulador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_especuladorActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
        jLabel1.setText("Jugador");
        jLabel1.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jg_especulador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jg_encarcelado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jg_saldo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jg_nom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_saldo, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                    .addComponent(txt_nombre)
                                    .addComponent(txt_encarcelado)
                                    .addComponent(txt_especulador)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panel_propiedades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jg_nom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jg_saldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_saldo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jg_encarcelado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_encarcelado, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jg_especulador)
                    .addComponent(txt_especulador, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_propiedades, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_encarceladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_encarceladoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_encarceladoActionPerformed

    private void txt_especuladorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_especuladorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_especuladorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jg_encarcelado;
    private javax.swing.JLabel jg_especulador;
    private javax.swing.JLabel jg_nom;
    private javax.swing.JLabel jg_saldo;
    private javax.swing.JPanel panel_propiedades;
    private javax.swing.JTextField txt_encarcelado;
    private javax.swing.JTextField txt_especulador;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_saldo;
    // End of variables declaration//GEN-END:variables
}
