/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author pc
 */
import civitas.TituloPropiedad;
public class PropiedadPanel extends javax.swing.JPanel {
    TituloPropiedad tituloPropiedad;
    /**
     * Creates new form PropiedadPanel
     */
    public PropiedadPanel() {
        initComponents();
    }
    void setPropiedad(TituloPropiedad prop)
    {
        tituloPropiedad=prop;
        txt_hipotecada.setText(Boolean.toString(prop.getHipotecado()));
        txt_nom_prop.setText(prop.getNombre());
        txt_num_casas.setText(Integer.toString(prop.getNumCasas()));
        txt_num_hoteles.setText(Integer.toString(prop.getNumHoteles()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_nom_propiedad = new javax.swing.JLabel();
        lb_num_casas = new javax.swing.JLabel();
        lb_num_hoteles = new javax.swing.JLabel();
        lb_hipotecada = new javax.swing.JLabel();
        txt_num_casas = new javax.swing.JTextField();
        txt_nom_prop = new javax.swing.JTextField();
        txt_num_hoteles = new javax.swing.JTextField();
        txt_hipotecada = new javax.swing.JTextField();

        lb_nom_propiedad.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        lb_nom_propiedad.setText("Nombre:");
        lb_nom_propiedad.setEnabled(false);

        lb_num_casas.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        lb_num_casas.setText("Nº Casas: ");
        lb_num_casas.setEnabled(false);

        lb_num_hoteles.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        lb_num_hoteles.setText("Nº Hoteles: ");
        lb_num_hoteles.setEnabled(false);

        lb_hipotecada.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        lb_hipotecada.setText("Hipotecada: ");
        lb_hipotecada.setEnabled(false);

        txt_num_casas.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        txt_num_casas.setEnabled(false);
        txt_num_casas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_num_casasActionPerformed(evt);
            }
        });

        txt_nom_prop.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        txt_nom_prop.setEnabled(false);
        txt_nom_prop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nom_propActionPerformed(evt);
            }
        });

        txt_num_hoteles.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        txt_num_hoteles.setEnabled(false);
        txt_num_hoteles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_num_hotelesActionPerformed(evt);
            }
        });

        txt_hipotecada.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        txt_hipotecada.setEnabled(false);
        txt_hipotecada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hipotecadaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_num_hoteles)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lb_num_casas)
                        .addComponent(lb_nom_propiedad, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lb_hipotecada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_num_hoteles, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nom_prop, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_num_casas, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_hipotecada, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_nom_propiedad)
                    .addComponent(txt_nom_prop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_num_casas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_num_casas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_num_hoteles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_num_hoteles))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_hipotecada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_hipotecada))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_num_casasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_num_casasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_num_casasActionPerformed

    private void txt_nom_propActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nom_propActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nom_propActionPerformed

    private void txt_num_hotelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_num_hotelesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_num_hotelesActionPerformed

    private void txt_hipotecadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hipotecadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hipotecadaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lb_hipotecada;
    private javax.swing.JLabel lb_nom_propiedad;
    private javax.swing.JLabel lb_num_casas;
    private javax.swing.JLabel lb_num_hoteles;
    private javax.swing.JTextField txt_hipotecada;
    private javax.swing.JTextField txt_nom_prop;
    private javax.swing.JTextField txt_num_casas;
    private javax.swing.JTextField txt_num_hoteles;
    // End of variables declaration//GEN-END:variables
}
